sudo: true
dist: xenial 
services:
  - docker
language: python 
python:
  - "3.5"

before_install:
  - pip3 install cwltool
  - docker build -t biodemo .

script:
  # Both of these same tests, in Docker
  # Functional tests
  - docker run --entrypoint /biodemo/.travis/unit-test.sh biodemo
  # Unit tests
  - docker run --entrypoint /biodemo/functional_tests/biodemo-test.sh biodemo -p biodemo -d /biodemo/functional_tests/test_data -v

  # CWL definition test
  - cwltool biodemo.cwl --fasta_file functional_tests/test_data/two_sequence.fasta
